### ISSUE TITLE
Globe key (for swapping keyboards) is missing (on iPad mini)

### ISSUE THREAD

**Issue by aarppe** [giellalt/keyboard-crk#16]
In the current keyboard (on iPad mini), the globe key, the clicking of which shows the various possible keyboards one can choose from, is missing. Thus, one is not able to swap to any other keyboard, once one has selected crk under Divvun Dev.

However, the globe key is visible on another device, such as Android (running on a Lenovo tablet), though that keyboard has other problems.

**Comment by snomos** [comment]
@bbqsrc this is now also reported for other languages and form factors: `krl` on an iPhone.

**Comment by bbqsrc** [comment]
Yes, the device detection library needs to be replaced with a newer version that knows about the new devices.

**Comment by aarppe** [comment]
When this is missing, clicking the Globe key results in a one-way selection of a Divvun Dev keyboard, and then the only way to go back to a system keyboard is to uninstall Divvun Dev keyboards - with the result that I've not been confident in installing Divvun Dev Keyboards on most other people's mobile devices. If the globe key would work, but one of the Divvun keyboards wouldn't be satisfactory, one could just swap back to one's old keyboards - but with the Globe key missing, one is stuck.

So updating the device detection library would be most welcome.

**Comment by aarppe** [comment]
This would appear to be connected with #9.

**Comment by aarppe** [comment]
It would seem that this particular issue has been resolved with the recent release of Divvun Dev Keyboards.

But the issue of recognizing the device to select the appropriate keyboard layout still persists (#9), i.e. instead of a 9-inch layout without the number/symbols row on my iPad mini, I'm still seeing the 11/12-inch iOS layout, cf. 
![nitatoskânân nikî-nitawi-wâpamâwak](https://user-images.githubusercontent.com/15003407/208267154-a174f5ca-a037-49fb-945e-edaca535161d.png)

**Comment by snomos** [comment]
Fixed in release 1.0.1.
