### ISSUE TITLE
Speller won't load on iOS

### ISSUE THREAD

**Issue by snomos** [giellalt/keyboard-crk#4]
When the keyboard is selected, it presents an option to install the speller:

![IMG_3083](https://user-images.githubusercontent.com/1255285/169259265-51ce175c-5a5f-40de-9e09-d0104eb6dda6.PNG)

But then it fails when downloading it:

![IMG_3086](https://user-images.githubusercontent.com/1255285/169259542-6318947f-84f1-4c41-aa31-0e60e36201fb.PNG)

Any idea what could be wrong, @bbqsrc ?

Reported by @aarppe.

**Comment by bbqsrc** [comment]
No, I'll add it to the list of things to cry about today.

**Comment by snomos** [comment]
This is fixed in the latest release.
