### ISSUE TITLE
Divvun Dev keyboard does not present suggestion when writing on Android

### ISSUE THREAD

**Issue by Trondtr** [giellalt/keyboard-crk#5]
To repeat:
1. Install Plains Cree keyboard with SRO (Latin) and with Syllabics 
2. Choosing SRO, add text, click on it, see that it works as normal (suggesting 3 forms in the line over the keyboard)
3. Choosing syllabics, add text, click on it, see that it does **NOT** suggest any forms in this line.

====

Update: This report was from yesterday. I now repeat the test (text below), and now **neither** of the keyboards give suggestion.

The  keyboards are Divvun Dev, installed June 5th 2022.

Test:
kinitohtênaw
kikâwînaw askiy opahkahokowin
kinitohtênaw itwêwina
kinitohtawânawak kêhtê-ayak
êkwa kinitohtâsonawn ekwa 

ᓂᐢᑕᒼ ᑭᓂᑐᐦᑌᓇᐤ
ᑭᑳᐑᓇᐤ ᐊᐢᑭᐩ ᐅᐸᐦᑲᐦᐅᑯᐏᐣ
ᑭᓂᑐᐦᑌᓇᐤ ᐃᑘᐏᓇ
ᑭᓂᒣᓇᓇᑐᐦᑕᐚᓇᐘᐠ ᑫᐦᑌ ᐊᔭᐠ
ᐁᑿ ᑭᓂᑐᐦᑖᓱᓇᐤ

First we listen
To the heartbeat of mother earth
We listen to the words
We listen to the elders
Then we listen to ourselves
nitêmak nipâwak ohcî maskwacîsihk

**Comment by Trondtr** [comment]
i should probably stop commenting here. Now, the crk SRO suggesting mechaniam works perfectly.

The crk syllabics does work as well, but not optimally so. two out of three suggestions are latin capital letter words, probably not what we want.

**Comment by aarppe** [comment]
Still, sometimes the crk-SRO keyboard speller does work on an Android device, and then at other times, the speller functionality seems to be missing for no explicit reason.

**Comment by snomos** [comment]
This should be fixed now. Closing.
